Changes for port to macOS
savamarc/LatMRG pull request #9
Opened 2021-03-24 02:46 UTC by o-nc

These changes were needed to port LatMRG to my macOS system.

I changed the type of m1, m2, m3 in ParamReaderExt to long long to match the type of ParamReader in latticetester and thus prevent a compilation error on my system.

2021-03-24 03:47 UTC, savamarc requested changes
Je mets "Request changes", mais c'est vraiment une formalité pour voir comment les code reviews fonctionnent sur github.

2021-03-24 03:47 UTC, savamarc commented on include/latmrg/ParamReaderExt.h
> +      long long m1, m2, m3;
`std::int64_t` comme dans LatticeTester.
De manière générale, évite les types long, long long et int sauf si tu es absolument certain que ça ne va pas overflow.

Comme la précision des entiers peut être importante dans ce programme, utilise les types à largeur fixée et le compilateur va aussi fonctionner sur tous les systèmes en faisant la bonne substitution de type.

2021-03-24 03:47 UTC, savamarc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
Ajoute un overload dans LatticeTester à la place de faire un static cast vers ZZ.

```
inline void conv(int&x, long a) {
unsigned y = (unsigned) a; x = static_cast<int>(y);
}
```
J'ai tiré le code directement de NTL.

2021-03-24 12:10 UTC, o-nc commented on include/latmrg/ParamReaderExt.h
> +      long long m1, m2, m3;
Merci pour le commentaire. J'ai ajouté un commit pour faire la modification.

2021-03-24 12:17 UTC, o-nc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
En fait cette modification ne fonctionne pas sur ma machine. De plus, dans Util.h de latticetester, il y a déjà une fonction avec la signature `inline void conv(int &x, long long a)` que je devrais utiliser. En ajouter une de plus n'aiderait pas.

Le problème vient que l'on a deux namespaces différents avec le même nom (NTL de NTL et NTL de latticetester) et que je ne sais pas comment dire au compilateur d'aller dans NTL de latticetester. Si j'écris `NTL::conv<int>(m_lac[m_lac.getSize()-1])`, le compilateur cherche dans le namespace NTL de la librairie NTL. Il va trouver quand `m_lac[m_lac.getSize()-1] `est de type ZZ mais pas quand il est de type std::int64_t/long long.

Je vois cinq solutions possibles:

1. Faire comprendre à mon compilateur que `NTL::conv<int>(m_lac[m_lac.getSize()-1])` fait référence au namespace NTL de la librairie latticetester et non pas de la librairie NTL. Je ne sais pas comment faire ça ou même si c'est possible. Si je regarde un livre de référence sur c++, ça me dit d'éviter d'avoir deux namespaces du même nom, mais pas quoi faire si ça arrive... [Ce que stackoverflow a à dire sur le problème.](https://stackoverflow.com/questions/11480647/how-to-solve-two-conflicting-namespaces-with-the-same-name.)
2. Faire le `static_cast<NTL::ZZ>` et utiliser la fonction de la librairie NTL comme dans mon commit.
3. Créer une fonction différente dans latticetester qui aurait une implémentation pour un argument NTL::ZZ et une autre pour long long, par exemple `NTL::conv_int(NTL::ZZ)`. Ensuite, je réutilise cette fonction pour les quatre conversions vers int que LatMRG fait.
4. Bouger le namespace NTL de latticetester pour qu'il soit un sub namespace de latticetester. Il faudrait alors changer changer toutes les fonctions signatures de latticetester et latnetbuilder qui utilisent ce namespace.
5. Changer le nom du namespace de latticetester pour quelque chose comme LatticeTester_NTL. Il faut encore une fois changer toutes les fonctions signatures de latticetester et latnetbuilder qui utilisent ce namespace.


La solution 2 est la plus simple. La solution 3 est presque aussi simple. Les solutions 4 et 5 sont un assez gros 
inconvénient, mais possiblement les solutions les plus "clean".

2021-03-24 12:17 UTC, o-nc commented on include/latmrg/ParamReaderExt.h
> +      long long m1, m2, m3;
Merci pour le commentaire. J'ai ajouté un commit qui fait la modification.

2021-03-24 12:55 UTC, savamarc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
Je suis presque certain que c'est buggé, NTL::ZZ n'est pas un type simple, le compilateur ne pourra pas magiquement transformer un int en ZZ avec un static_cast.

En tant que tel, les namespaces ne rentrent pas en conflit.

Les trucs ont été fait comme ça pour étendre le le namespace NTL, pas pour être en parallèle. Tu peux avoir plusieurs fonctions dans un même namespace et pas dans le même fichier. Il faut que tu vois les fonctions dans le namespace NTL dans LatticeTester comme faisant partie de NTL.

Si tu ne trouves pas l'overload qu'il te faut dans LatticeTester, il te manque probablement quelques `#include`.

2021-03-24 23:10 UTC, savamarc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
@o-nc Plus j'y repense et plus j'ai la certitude que c'est buggé de faire ce static_cast.

La vraie solution clean est de trouver l'include qu'il manque (normalement l'overload manquant ici est dans `latticetester/Util.h`). Voir si ça fonctionne en faisant l'include explicitement.

Si c'est vraiment encore un problème, fait un static_cast vers long à la place (parce que c'est ce que ça ferait de toute façon).

2021-03-24 23:11 UTC, savamarc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
@o-nc Plus j'y repense et plus j'ai la certitude que c'est buggé de faire ce static_cast. As-tu testé le code?

La vraie solution clean est de trouver l'include qu'il manque (normalement l'overload manquant ici est dans `latticetester/Util.h`). Voir si ça fonctionne en faisant l'include explicitement.

Si c'est vraiment encore un problème, fait un static_cast vers long à la place (parce que c'est ce que ça ferait de toute façon).

2021-03-25 17:51 UTC, o-nc commented on include/latmrg/MMRGLattice.h
> +      int maxIndiceLac = NTL::conv<int>(static_cast<NTL::ZZ>(m_lac[m_lac.getSize()-1]));
Je n'ai pas testé. Tu as raison que c'est buggé par contre. Ça ne fait aucun sens. J'étais trop rusty en c++ (même chose pour mon idée avec deux namespace du même nom). J'ai ajouté un 3ème commit qui règle le problème dans latticetester.

J'ai regardé le code après le travail du preprocessor avec `g++ -E Util.h`. Le problème n'est pas qu'il manque un #include car tout le code nécessaire est présent. Le problème est l'ordre du code.

Selon le standard C++11 14.3.7/6 

> If a template, a member template or the member of a class template is explicitly specialized then that specialization shall be declared before the first use of that specialization that would cause an implicit instantiation to take place

En gros, mon compilateur arrête de cherché dans le code dès qu'il voit 

> `template<class T, class S>
> T conv(const S& a)
> {
>    T x;
>    conv(x, a);
>    return x;
> }`

 à la fin de NTL/tools.h. Toutes nos fonctions NTL::conv() sont écrites après NTL/tools.h et ne seront pas trouvées si on les appelle avec une signature comme `NTL::conv<int>(second_argument)`. Il faut soit faire `int temp; NTL::conv(temp, second_argument)` soit déclarer la specialization du template avant que le compilateur utilisera la specialization dans NTL/tools.h.

J'ai choisi de déclarer la specialization dans Util.h avant d'inclure NTL/tools.h car c'est plus clean et plus facile d'ajouter une déclaration vs changer le code partout. Pour bien faire, j'aurais fait un nouveau fichier juste pour la déclaration et #include "new_file" dans Util.h avant NTL/tools.h. Je ne voulais pas ajouter un nouveau fichier avant d'avoir parlé plus avec Pierre par contre.

Je crois que ça termine ce Pull request. Merci encore pour tes commentaires Marc-Antoine.

2021-03-26 22:01 UTC, savamarc approved these changes
Good! De ce que je comprends des templates, je suis pas trop certain que l'explication que tu as trouvée est la bonne. Techniquement, on ne fait pas la spécialisation explicite du template ici parce qu'on n'en a pas besoin (on utilise le code dans la définition du template donc le template sera compilé et instancié au moment où on l'utilise). Ce qui se passe, c'est plus que quand il fait la spécialisation implicite du template il regarde seulement le code qui vient avant le template.

Ceci dit, si ça marche, c'est good enough pour moi.

2021-03-26 22:02 UTC, merged